In [2]:
import numpy as np

nums = np.array([[5, 3, 7],
                 [6, 5, 6],
                 [1, 2, 5]])

print("Original array:")
print(nums)

nums[nums < 5] = 10

print("\nModified array:")
print(nums)

Original array:
[[5 3 7]
 [6 5 6]
 [1 2 5]]

Modified array:
[[ 5 10  7]
 [ 6  5  6]
 [10 10  5]]
